---
title: "Meditations for Mortals | Mar-Apr 2025"
sidebar: false
page-layout: full
toc: false
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../../materials.ejs
date-format: DD MMM, YYYY
---

### Meditations for Mortals: A Guide to Life, Death and Beyond

#### by Oliver Burkeman

---

##### 24 March 2025 to 20 April 2025

:::: {.columns}

::: {.column width="58%"}
:::{.callout-note icon="false"}
##### About the Book

Interesting notes on how working backwards from the realization that we all only have so much time and will never really get everything done can actually be empowering. You can find the book at all the usual places, and the for the purposes of our discussion, using either the book or the audiobook (which, in this case, is narrated by the author) would work well. 
:::

:::{.callout-tip icon="false"}
##### Target Audience

Anyone who finds the premise of this book interesting and can commit about half an hour daily to reading a chapter. There are a lot of podcasts and interviews and book reviews that you can find around this book to help you decide if it's for you. 

A reading of 4000 weeks is not necessary, this book holds up well standalone, although the two books do share a common theme. If you are curious about the other book, [this talk](https://www.youtube.com/watch?v=i9juUTtvCzI) is a nice overview.

:::

:::

::: {.column width="42%"}
:::{.callout-caution icon="false"}
##### Timings and Venue

We meet on Zoom at 9PM IST for about 20 minutes every day according to the schedule below. Here is a link to a [WA group](https://chat.whatsapp.com/DuThNGufqc4Lepmq1imVMA) where we discuss more and post announcements. 

The Zoom details are as follows:

Meeting ID: `938 5856 0752`<br>
Passcode: `4000`

See you there!
:::
:::

::::

## Reading Schedule

::: {#lectures-listing}
:::
