---
title: "Magical Mathematics | Spring 2025"
sidebar: false
page-layout: full
toc: false
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../../materials.ejs
date-format: DD MMM, YYYY
---

### Magical Mathematics: The Mathematical Ideas That Animate Great Magic Tricks

#### _Persi Diaconis and Ronald Graham_

---

##### 01 Mar 2025 to 21 Mar 2025

:::{.callout-note icon="false   "}
##### About the Book

[Magical Mathematics](https://www.amazon.in/Magical-Mathematics-Mathematical-Animate-Tricks/dp/0691169772) reveals several rich mathematical ideas that can be used to drive several magical effects with cards and more. 

The book is roughly in two parts, the first focused on card magic and the rest focused on magic with other artifcats, juggling, and several cool stories. In this reading, we'll go over the first half (up to chapter 7, if all goes according to plan).

:::

:::{.callout-tip icon="false"}
##### Prerequisites

Basic comfort with mathematical reasoning. No prior experience with magic is required!
:::

:::{.callout-caution icon="false"}
##### Logistics

- We meet every day (with one weekend break) according to the schedule below at **9PM IST**.
- Any changes will be announced here and on this [whatsapp group](https://chat.whatsapp.com/GDyCCsJugLWFIo3bh5icIG). 
- Recordings from the sessions will show up [here](https://www.youtube.com/watch?v=MYhZazMcSQ4&list=PLadhlDF3zdvt4ehc9R2o_rukOXFexYltg). 
- Join us on Zoom via [this link](https://iitgn-ac-in.zoom.us/j/93583628138?pwd=q4xBLipLCg18ahmYp1NkLgWaJFUlHc.1) or by using meeting ID `935 8362 8138` and passcode `hummer`.
- Subscribe to the Google Calendar for these sessions [here](https://calendar.google.com/calendar/embed?src=504186f9214adf7ea1190318cd7eb894dbc85a66db0e6841d3630c98bd5095d2%40group.calendar.google.com&ctz=Asia%2FKolkata) (if you are already on a Google account) or download an ICS file [here](https://calendar.google.com/calendar/ical/504186f9214adf7ea1190318cd7eb894dbc85a66db0e6841d3630c98bd5095d2%40group.calendar.google.com/public/basic.ics).
:::

## Reading Schedule

::: {#lectures-listing}
:::